Vagrant.configure(2) do |config|
 config.vm.provision "shell", inline: "echo Hello"
 config.vm.network "private_network", type: "dhcp"

 config.vm.define "web", primary:true do |web|
  web.vm.box = "ubuntu/trusty64"
  web.vm.hostname ="NodeEx1"
  web.vm.provision "shell", path: "provision.sh" 
 end

  config.vm.define "db" do |db|
   db.vm.box = "ubuntu/trusty64"
  db.vm.hostname ="NodeEx2"
  db.vm.provision "shell", path: "provision.sh"   
  end
  
end
